
<html> 
  <head> 
    <title>Single Sign On Service</title> 
    <link rel="stylesheet" href="/css/tw.css" />   
    <script type="text/javascript" src="/js/jquery.js"></script> 
    <script type="text/javascript" src="/js/customFunction.js"></script> 
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
  </head> 
  <body> 
 
    <div class="container"> 
      <div class="topbar-wrapper" style="z-index: 5; "> 
	<div class="topbar"> 
	  <div class="fill"> 
	    <div class="container"> 
	      <h3> 
		<a href="#">Go-Managed</a> 
	      </h3> 
	    </div> 
	  </div> 
	</div> 
      </div> 
 
      <div class="spacer" style="margin-top:100px;">&nbsp;</div> 
 
      %s
      
    <script>
      var focus = '%s' ;
    </script>
  </body> 
</html> 
