<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html> 
  <head> 
    <link rel="stylesheet" type="text/css" href="/css/template.css" /> 
    <script type="text/javascript" language="JavaScript">
      <!--
		if(document.layers) {document.write("<style>td{padding:0px;}<\/style>")}
	// -->
    </script> 
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
    <meta http-equiv="Pragma" content="no-cache" /> 
	<meta http-equiv="Cache-Control" content="no-cache" /> 
	<meta http-equiv="Pragma-directive" content="no-cache" /> 
	<meta http-equiv="Cache-Directive" content="no-cache" /> 
	<meta name="robots" content="noindex,follow" /> 
	<link rel="shortcut icon" href="http://www.isvtec.com/infogerance/ticket/images/favicon.ico" type="image/x-icon" /> 
	<title>Infogerance ISVTEC</title> 
	<script type="text/javascript" src="/js/jquery.js"></script> 
	<script type="text/javascript" src="/js/customFunction.js"></script> 
  </head> 
  <body> 
    <div id="contenu"> 
      <table class="header" border="0" cellpadding="0" cellspacing="0"> 
	<tr> 
	  <td height="10" colspan="3" style="background-color:#ab1e23;"></td> 
	</tr> 
	<tr style="background-color:#ab1e23;"> 
	  <td width="22"></td> 
          <td width="183" height="78">
	    <a href="http://www.isvtec.com/">
	      <img src="../image/logo.gif" width="183" height="78" alt="ISVTEC" />
	    </a>
	  </td> 
          <td> 
            <table width="100%" style="height:78px;" border="0" cellpadding="0" cellspacing="0"> 
              <tr> 
            	<td colspan="2" align="right" valign="top"></td> 
              </tr> 
              <tr> 
            	<td height="30" align="center" valign="middle"> 
            	  <table width="100%" border="0" cellpadding="0" cellspacing="1"> 
            	    <tr> 
            	      <td nowrap="nowrap">
			<a href="http://www.isvtec.com/" class="mainlevel" id="active_menu">Accueil</a>
			<a href="http://www.isvtec.com/infogerance" class="mainlevel" >Infogérance</a>
			<a href="http://www.isvtec.com/developpement" class="mainlevel" >Développement</a>
			<a href="http://www.isvtec.com/formations" class="mainlevel" >Formations</a>
		      </td> 
            	    </tr> 
            	  </table> 
            	</td> 
              </tr> 
	    </table> 
	  </td> 
	</tr> 
      </table> 
      <table width="100%" border="0" cellpadding="0" cellspacing="0" style="margin-top:10px;"> 
	<tr> 
          <td width="22" style="padding:1px;"></td> 
          <td width="120" valign="top" class="header_tagline" style="padding:1px;"> 
	    Network&nbsp;Services
	  </td> 
          <td width="700" style="padding:1px;"></td> 
          <td height="20" valign="top" style="padding:1px;"> 
            <table width="100%" cellspacing="1" cellpadding="0" border="0"> 
	      <tr> 
		<td nowrap="nowrap"> 
		  <a id="active_menusub" class="mainlevelsub" href="http://www.isvtec.com/qui-sommes-nous">Qui sommes nous</a> 
		  <span class="mainlevelsub"> | </span> 
		  <a class="mainlevelsub" href="http://www.isvtec.com/contactez-nous">Contactez-nous</a> 
		</td> 
	      </tr> 
	    </table> 
          </td> 
          <td width="22" style="padding:1px;"></td> 
	</tr> 
      </table>
      <br />
      <div align="center"></div> 
      <!-- debut form -->

      %s


      <!-- fin form -->


      <br />
 
      <div id="first_footer"> 
	<a class="mainlevelfooter" href="http://www.isvtec.com/contributions">Contributions</a> 
	<span class="mainlevelfooter"> | </span> 
	<a class="mainlevelfooter" href="http://www.isvtec.com/contactez-nous">Contactez-nous</a> 
      </div> 
 
      <div id="second_footer"> 
	<span class="copyright">&copy; 2003-2011 ISVTEC All Rights Reserved</span> 
      </div> 
 
    </div> 
    <br /> 
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
      <tr valign="top">
	<td></td>
	<td> 
	  <div align="right"></div> 
	</td>
      </tr>
   </table> 
    <script>
      var focus = '%s' ;
    </script>
  </body> 
</html> 
