#!/bin/bash
# Copyright (C) Cyril Bouthors - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Cyril Bouthors <cyril@boutho.rs>, 2003-2020

# Error if code coverage != 100%

report_file=$1

set -e -o pipefail -u

if [ -z "$report_file" ]
then
  echo "$0: too few argument" >&2
  exit 1
fi

if [ ! -f "$report_file" ]
then
  echo "$0: unable to open file $report_file" >&2
  exit 1
fi

phpunit_version=$(phpunit --version | awk '/^PHPUnit/ {print $2}' \
  | cut -d. -f1,2)

if [ -z "$phpunit_version" ]
then
  echo "$0: unable to fetch PHPUnit version" >&2
  exit 1
fi

case "$phpunit_version" in
  '3.4')
    coverage_percentage=$(head -63 $report_file | tail -1 | cut -d\" -f10)
  ;;

  '3.6')
    coverage_percentage=$(awk -F\" '/coverBarOutline/ {print $4; exit}' \
      "$report_file")
  ;;

  '4.2')
    coverage_percentage=$(grep -A3 Total $report_file \
      | awk '/sr-only/ {print $2}' | cut -d\> -f2)
  ;;

  '5.1'|'5.4')
    coverage_percentage=$(head -46 $report_file |tail -1 | cut -d\" -f6)%
  ;;

  '7.5')
    coverage_percentage=$(head -47 $report_file |tail -1 | cut -d\" -f6)%
  ;;

  *)
    echo "$0: unknown PHPUnit version $phpunit_version" >&2
    exit 1
esac

echo "Coverage report: $coverage_percentage"

# Check coverage percentage level
if [ "$coverage_percentage" != '100.00%' ]
then
  exit 1
fi
