#!/bin/sh
#
# Copyright (C) 2010 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]
then
    rm -f /etc/apache2/conf.d/cybsso.conf

    # Reload webserver in any case, configuration might have changed Redirection
    # of 3 is needed because Debconf uses it and it might be inherited by
    # webserver. See bug #446324.
    /etc/init.d/apache2 reload 3>/dev/null || true

    if [ "$1" = "purge" ]
    then
	rm -rf /etc/cybsso /var/lib/cybapi
    fi
fi

#DEBHELPER#

exit 0
